### ISSUE TITLE
Should the building list be in a file or in a JavaScript source?

### ISSUE THREAD

**Issue by emmiegit** [ammongit/ucr-class-map#43]
It seems like having the building list in its own file is better in terms of program structure, but there are potential issues with jQuery loading files.

What are the pros and cons of both? Which should we choose?

**Comment by ghost** [comment]
Depends on if you want to be a peasant or not. Hard coding data is a peasant act commited by communists. Instead of modifying our js files, it is always good practice to have data in a seperate file to be modified when necessary. Although js is ran on demand by the website and doesnt need compilation so you can modify the js files whenever, one should always use data files to store constant data, not their code.
